//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int Id { get; set; }
    public string ProductName { get; set; }
    public string SellerInternalId { get; set; }
    public Nullable<decimal> Price { get; set; }
}

public partial class Review
{
    public int Id { get; set; }
    public Nullable<int> ProductId { get; set; }
    public string Reviewer { get; set; }
    public Nullable<bool> VerifiedPurchaser { get; set; }
    public string ReviewTitle { get; set; }
    public Nullable<int> Stars { get; set; }
    public string ReviewText { get; set; }
    public Nullable<System.DateTime> ReviewDate { get; set; }
}
